@startuml HEMOBILE

class Hemocentro {
    -nome: String
    -endereço: String
    -estoqueBolsas: String
    -listaAgendamentos: String
    -listaNotificações: String
    -listaExames: String
}

class Usuário {
    -id: int
    -email: String
    -senha: String
    -nome: String
    -idade: Int
    -CPF: String
    -endereço: String
    -sangue: String

    +FazerAutenticação(email, senha)
    +RealizarPréTriagem()
}

class Doador {
    -ativoDoar: boolean
    -dataUltimaDoacao: int
    +AgendarDoação()
    +VisualizarExames()
    +VisualizarCarteira()
}

class Receptor {
  -urgencia: String
  -dataSolicitacao: int
  -statusSaude: String
  +SolicitarDoação()
  +AtualizarDoacao()
}

class PréTriagem {
  -id: int
  -resultado: boolean
  -relatorio: String
}

class Agendamento {
  -data: int
  -hora: int
  -local: String
  -status: boolean
}

class Doação {
  -id: int
  -dataDoacao: int
  -volume: double
  -tipoSanguineo: String
  +RegistrarDoacao(doador, volume, tipoSanguineo)
  +VerificarDoacao()
  +AtualizarVolume()
}

class Notificação {
  -id: int
  -mensagem: String
  -dataEnvio: int
  -status: boolean
  +EnviarNotificacao(usuario, mensagem)
  +MarcarComoLida()
}

class Carteira {
  -id: int
  -historicoDoacoes: String
  -examesRealizados: String
  +AdicionarDoacao(doacao)
  +AdicionarExame(exame)
}

class Exames {
  -id: int
  -tipoExame: String
  -dataExame: int
  +RealizarExame(doador)
  +VerificarExame()
}

class HistóricoDoações {
  -id: int
  -doacoes: String
  +AdicionarDoacao(doacao)
  +ListarDoacoes()
}

Usuário <|-- Doador
Usuário <|-- Receptor

Hemocentro "1" o-- "0..*" Agendamento
Hemocentro "1" o-- "0..*" Exames
Hemocentro "1" o-- "0..*" Notificação

Receptor "1" --> "1" Hemocentro : Solicita doação
Notificação "1" --> "1" Usuário : Notifica

Doador "1" o-- "1" Carteira
Doador "1" o-- "0..*" HistóricoDoações
Doador "1" o-- "0..*" Exames
Doador "1" --> "0..*" Agendamento : Faz agendamento
Doador "1" --> "0..*" Doação : Realiza

Doador "1" --> "0..*" PréTriagem : Realiza
PréTriagem "1" --> "1" Hemocentro : Feita em

Carteira "1" --* "1" HistóricoDoações
HistóricoDoações "1" --* "0..*" Doação

@enduml
