@startuml HEMOBILE
start

title Solicitação de Doação

:O usuário solicita quando estiver precisando de doação;

:Hemocentro registra solicitação;

:Hemobile notifica doadores próximos cadastrados;
stop
@enduml